import { type Game, type InsertGame, GAME_CATEGORIES } from "@shared/schema";
import { randomUUID } from "crypto";

export interface IStorage {
  // Game operations
  getAllGames(): Promise<Game[]>;
  getGameById(id: string): Promise<Game | undefined>;
  getGamesByCategory(category: string): Promise<Game[]>;
  getTrendingGames(): Promise<Game[]>;
  getNewGames(): Promise<Game[]>;
  searchGames(query: string): Promise<Game[]>;
  createGame(game: InsertGame): Promise<Game>;
  updateGame(id: string, updates: Partial<Game>): Promise<Game | undefined>;
  deleteGame(id: string): Promise<boolean>;
  incrementPlays(id: string): Promise<void>;
}

export class MemStorage implements IStorage {
  private games: Map<string, Game>;

  constructor() {
    this.games = new Map();
    this.seedInitialData();
  }

  private seedInitialData() {
    // เกมที่สร้างขึ้นเองใน ASHURA Games - เล่นได้จริงทุกเกม
    const defaultGames = [
      {
        title: '3D Cube Runner',
        description: 'เกมวิ่งหลบสิ่งกีดขวางแบบ 3D ด้วย WebGL กราฟิกสุดล้ำ วิ่งไปข้างหน้าและหลบอุปสรรค',
        thumbnail: '/api/games/1/thumbnail',
        gameUrl: '/games/3d-cube-runner.html',
        gameFile: null,
        isEmbedded: false,
        category: 'action',
        rating: 50,
        plays: 18750,
        isNew: true,
        isTrending: true,
      },
      {
        title: 'Particle Explosion WebGL',
        description: 'เกมอนุภาคระเบิดสุดมันส์ด้วย WebGL เอฟเฟกต์สวยงาม คลิกเพื่อสร้างการระเบิดสีสัน',
        thumbnail: '/api/games/2/thumbnail',
        gameUrl: '/games/particle-explosion.html',
        gameFile: null,
        isEmbedded: false,
        category: 'arcade',
        rating: 49,
        plays: 12450,
        isNew: true,
        isTrending: true,
      },
      {
        title: '3D Racing WebGL',
        description: 'เกมแข่งรถ 3D สุดเร้าใจ ขับรถหลบคู่แข่ง ใช้บูสเตอร์ และแซงหน้าเพื่อคะแนนสูง',
        thumbnail: '/api/games/3/thumbnail',
        gameUrl: '/games/3d-racing-webgl.html',
        gameFile: null,
        isEmbedded: false,
        category: 'racing',
        rating: 50,
        plays: 21300,
        isNew: true,
        isTrending: true,
      },
  {
    title: 'Particle Explosion WebGL',
    description: 'เกมอนุภาคระเบิดสุดมันส์ด้วย WebGL เอฟเฟกต์สวยงาม คลิกเพื่อสร้างการระเบิดสีสัน',
    thumbnail: '/api/games/2/thumbnail',
    gameUrl: '/games/particle-explosion.html',
    gameFile: null,
    isEmbedded: false,
    category: 'arcade',
    rating: 49,
    plays: 12450,
    isNew: true,
    isTrending: true,
  },
  {
    title: '3D Racing WebGL',
    description: 'เกมแข่งรถ 3D สุดเร้าใจ ขับรถหลบคู่แข่ง ใช้บูสเตอร์ และแซงหน้าเพื่อคะแนนสูง',
    thumbnail: '/api/games/3/thumbnail',
    gameUrl: '/games/3d-racing-webgl.html',
    gameFile: null,
    isEmbedded: false,
    category: 'racing',
    rating: 50,
    plays: 21300,
    isNew: true,
    isTrending: true,
  },
  {
    title: '3D Space Invaders',
    description: 'เกมยิงอวกาศ 3D สุดมันส์ ยิงยานมนุษย์ต่างดาว เก็บพาวเวอร์อัพ และปกป้องโลก',
    thumbnail: '/api/games/4/thumbnail',
    gameUrl: '/games/space-invaders-3d.html',
    gameFile: null,
    isEmbedded: false,
    category: 'action',
    rating: 50,
    plays: 16800,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Neon Maze 3D',
    description: 'เขาวงกต 3D สุดล้ำ เดินทางผ่านเขาวงกตนีออน เก็บของสะสม และหาทางออก',
    thumbnail: '/api/games/5/thumbnail',
    gameUrl: '/games/neon-maze-3d.html',
    gameFile: null,
    isEmbedded: false,
    category: 'puzzle',
    rating: 50,
    plays: 14200,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Neon Platformer WebGL',
    description: 'เกมกระโดดข้ามแพลตฟอร์ม WebGL สุดสวย นีออนเอฟเฟกต์ เก็บเพชร หลีกเลี่ยงศัตรู',
    thumbnail: '/api/games/6/thumbnail',
    gameUrl: '/games/neon-platformer-webgl.html',
    gameFile: null,
    isEmbedded: false,
    category: 'action',
    rating: 50,
    plays: 18900,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Cyber Runner 3D',
    description: 'วิ่งผ่านเมืองไซเบอร์ 3D หลีกเลี่ยงสิ่งกีดขวาง เปลี่ยนเลน และสะสมคะแนนสูง',
    thumbnail: '/api/games/7/thumbnail',
    gameUrl: '/games/cyber-runner-3d.html',
    gameFile: null,
    isEmbedded: false,
    category: 'action',
    rating: 50,
    plays: 22400,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Quantum Shooter WebGL',
    description: 'เกมยิงควอนตัม WebGL ด้วยเอฟเฟกต์พิเศษ พาวเวอร์อัพ และศัตรูหลากหลาย',
    thumbnail: '/api/games/8/thumbnail',
    gameUrl: '/games/quantum-shooter-webgl.html',
    gameFile: null,
    isEmbedded: false,
    category: 'action',
    rating: 50,
    plays: 19600,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Galactic Defender 3D',
    description: 'เกมปกป้องกาแล็กซี่ 3D สุดอลังการ อาวุธหลากหลาย ศัตรูมากมาย และเอฟเฟกต์สุดตระการตา',
    thumbnail: '/api/games/9/thumbnail',
    gameUrl: '/games/galactic-defender-3d.html',
    gameFile: null,
    isEmbedded: false,
    category: 'action',
    rating: 50,
    plays: 25800,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Crystal Caverns 3D',
    description: 'สำรวจถ้ำคริสตัล 3D มหัศจรรย์ เก็บอัญมณี หลีกเลี่ยงอันตราย และเปิดเส้นทางลับ',
    thumbnail: '/api/games/10/thumbnail',
    gameUrl: '/games/crystal-caverns-3d.html',
    gameFile: null,
    isEmbedded: false,
    category: 'adventure',
    rating: 50,
    plays: 18900,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Neural Network 3D',
    description: 'สำรวจโครงข่ายประสาทเทียมในมิติสาม พัฒนาทักษะการวิเคราะห์และการคิดเชิงระบบ',
    thumbnail: '/api/games/11/thumbnail',
    gameUrl: '/games/neural-network-3d.html',
    gameFile: null,
    isEmbedded: false,
    category: 'puzzle',
    plays: 0,
    rating: 45,
    isNew: true,
    isTrending: false
},
    {
        title: 'Volleyball Championship',
        description: 'เกมวอลเลย์บอลสุดมันส์! ตีลูกให้แรงด้วยปุ่มพิเศษ แข่งขันกับเพื่อนในสนามวอลเลย์บอลจำลอง',
        thumbnail: '/api/games/12/thumbnail',
        gameUrl: '/games/volleyball-championship.html',
        gameFile: null,
        isEmbedded: false,
        category: 'sports',
        plays: 8500,
        rating: 47,
        isNew: true,
        isTrending: true
    },
  {
    title: 'Space Mining 3D',
    description: 'เกมขุดแร่ในอวกาศ 3D ใช้เครื่องมือเจาะ เก็บแร่ธาตุ หลีกเลี่ยงอุกกาบาต',
    thumbnail: '/api/games/13/thumbnail',
    gameUrl: '/games/space-mining-3d.html',
    gameFile: null,
    isEmbedded: false,
    category: 'action',
    rating: 50,
    plays: 14200,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Cosmic Defender WebGL',
    description: 'เกมปกป้องจักรวาล WebGL มีระบบโล่พลังงาน อาวุธอัพเกรด และศัตรูหลากหลาย',
    thumbnail: '/api/games/14/thumbnail',
    gameUrl: '/games/cosmic-defender-webgl.html',
    gameFile: null,
    isEmbedded: false,
    category: 'action',
    rating: 50,
    plays: 19700,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Snake Enhanced Pro',
    description: 'เกมงูสุดพิเศษ มีระบบเลเวล อาหารพิเศษ อนุภาคสวยงาม และเอฟเฟกต์ตัวเก่าด้วยกราฟิกแบบไล่สี',
    thumbnail: '/api/games/15/thumbnail',
    gameUrl: '/games/snake-enhanced.html',
    gameFile: null,
    isEmbedded: false,
    category: 'action',
    rating: 50,
    plays: 22150,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Snake Game Classic',
    description: 'เกมงูคลาสสิกที่ทุกคนเคยเล่น กินจุดเติบโต หลีกเลี่ยงตัวเอง',
    thumbnail: '/api/games/16/thumbnail',
    gameUrl: '/games/snake.html',
    gameFile: null,
    isEmbedded: false,
    category: 'action',
    rating: 48,
    plays: 15250,
    isNew: false,
    isTrending: true,
  },
  {
    title: 'Tetris Enhanced Pro',
    description: 'เกม Tetris สุดพิเศษ เอฟเฟกต์อนุภาค กราฟิกไล่สี ระบบเลเวลใหม่ และการแสดงผลที่สวยงาม',
    thumbnail: '/api/games/17/thumbnail',
    gameUrl: '/games/tetris-enhanced.html',
    gameFile: null,
    isEmbedded: false,
    category: 'puzzle',
    rating: 50,
    plays: 19650,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Tetris Rush',
    description: 'เกม Tetris คลาสสิกที่ไม่มีวันล้าสมัย จัดบล็อกให้เต็มแถว',
    thumbnail: '/api/games/18/thumbnail',
    gameUrl: '/games/tetris.html',
    gameFile: null,
    isEmbedded: false,
    category: 'puzzle',
    rating: 50,
    plays: 12800,
    isNew: false,
    isTrending: true,
  },
  {
    title: 'Space Shooter',
    description: 'เกมยิงเอเลี่ยนในอวกาศสุดมันส์ กราฟิกสวยและเล่นลื่น',
    thumbnail: '/api/games/19/thumbnail',
    gameUrl: '/games/space-shooter.html',
    gameFile: null,
    isEmbedded: false,
    category: 'action',
    rating: 47,
    plays: 8920,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Flappy Bird',
    description: 'เกมบินผ่านท่อที่ยากแต่เสพติด เกมที่ทำให้โลกกลับมาฮิตอีกครั้ง',
    thumbnail: '/api/games/20/thumbnail',
    gameUrl: '/games/flappy-bird.html',
    gameFile: null,
    isEmbedded: false,
    category: 'action',
    rating: 49,
    plays: 11350,
    isNew: true,
    isTrending: true,
  },
  {
    title: '2048',
    description: 'เกมปริศนาตัวเลขที่ทำให้ติดไม่หยุด รวมตัวเลขให้ได้ 2048',
    thumbnail: '/api/games/21/thumbnail',
    gameUrl: '/games/2048.html',
    gameFile: null,
    isEmbedded: false,
    category: 'puzzle',
    rating: 46,
    plays: 9780,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Bubble Shooter',
    description: 'เกมยิงบอลสีเพื่อจับคู่สีเดียวกัน เล่นง่าย สนุก ผ่อนคลาย',
    thumbnail: '/api/games/22/thumbnail',
    gameUrl: '/games/bubble-shooter.html',
    gameFile: null,
    isEmbedded: false,
    category: 'casual',
    rating: 43,
    plays: 6540,
    isNew: false,
    isTrending: false,
  },
  {
    title: 'Racing Rush',
    description: 'เกมขับรถแข่งสุดเร้าใจ หลบหลีกการจราจร พุ่งไปให้ไกลที่สุด',
    thumbnail: '/api/games/23/thumbnail',
    gameUrl: '/games/racing-rush.html',
    gameFile: null,
    isEmbedded: false,
    category: 'racing',
    rating: 45,
    plays: 7210,
    isNew: false,
    isTrending: false,
  },
  {
    title: 'Pong Classic',
    description: 'เกมปิงปองคลาสสิกตัวแรกของโลก เล่น 2 คน ควบคุมไม้ตีไปมา เกมที่เริ่มต้นยุคเกม',
    thumbnail: '/api/games/24/thumbnail',
    gameUrl: '/games/pong-classic.html',
    gameFile: null,
    isEmbedded: false,
    category: 'arcade',
    rating: 48,
    plays: 8950,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Breakout Retro',
    description: 'เกมทำลายอิฐคลาสสิก ใช้ลูกบอลและไม้ตีทำลายอิฐทุกแผ่น เกมที่สร้างแรงบันดาลใจให้เกมยุคใหม่',
    thumbnail: '/api/games/25/thumbnail',
    gameUrl: '/games/breakout-retro.html',
    gameFile: null,
    isEmbedded: false,
    category: 'arcade',
    rating: 47,
    plays: 12300,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Connect Four',
    description: 'เกมเรียงหมากครุย 4 เม็ดติดกัน เล่น 2 คน วางหมากเป็นเส้นตรง แนวตั้ง แนวนอน หรือแนวทแยงมุม',
    thumbnail: '/api/games/26/thumbnail',
    gameUrl: '/games/connect-four.html',
    gameFile: null,
    isEmbedded: false,
    category: 'puzzle',
    rating: 45,
    plays: 6780,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Tic Tac Toe',
    description: 'เกม OX คลาสสิก เล่น 2 คน เรียง X หรือ O ให้ได้ 3 เม็ดติดกัน เกมง่ายๆ ที่ทุกคนรู้จัก',
    thumbnail: '/api/games/27/thumbnail',
    gameUrl: '/games/tic-tac-toe.html',
    gameFile: null,
    isEmbedded: false,
    category: 'puzzle',
    rating: 44,
    plays: 5420,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Pac-Man Adventure',
    description: 'เกมผีน้อยสุดคลาสสิก กินจุดหลบผี เก็บผลไม้พิเศษ และเคลียร์เขาวงกตทุกด่าน',
    thumbnail: '/api/games/28/thumbnail',
    gameUrl: '/games/pacman-adventure.html',
    gameFile: null,
    isEmbedded: false,
    category: 'arcade',
    rating: 49,
    plays: 14600,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Asteroid Shooter',
    description: 'เกมยิงดาวเคราะห์น้อยคลาสสิก หมุนยานอวกาศยิงทำลายอุกกาบาต หลีกเลี่ยงการชน',
    thumbnail: '/api/games/29/thumbnail',
    gameUrl: '/games/asteroid-shooter.html',
    gameFile: null,
    isEmbedded: false,
    category: 'action',
    rating: 46,
    plays: 9850,
    isNew: true,
    isTrending: false,
  },
  {
    title: 'Memory Cards',
    description: 'เกมจับคู่การ์ดที่ฝึกความจำ เล่นง่าย เหมาะสำหรับทุกเพศทุกวัย',
    thumbnail: '/api/games/30/thumbnail',
    gameUrl: '/games/memory-cards.html',
    gameFile: null,
    isEmbedded: false,
    category: 'casual',
    rating: 41,
    plays: 4890,
    isNew: false,
    isTrending: false,
  },
  {
    title: 'Puzzle Blocks',
    description: 'เกมปริศนาจิ๊กซอว์บล็อก วางชิ้นส่วนให้เข้าที่ ฝึกสมอง',
    thumbnail: '/api/games/31/thumbnail',
    gameUrl: '/games/puzzle-blocks.html',
    gameFile: null,
    isEmbedded: false,
    category: 'puzzle',
    rating: 42,
    plays: 3650,
    isNew: false,
    isTrending: false,
  },
  {
    title: 'Tower Defense 3D',
    description: 'เกมป้องกันหอคอย 3D ที่มีศัตรูหลายประเภท อาวุธอัพเกรดได้ และกลยุทธ์สุดล้ำ',
    thumbnail: '/api/games/32/thumbnail',
    gameUrl: '/games/tower-defense-3d.html',
    gameFile: null,
    isEmbedded: false,
    category: 'strategy',
    rating: 49,
    plays: 12400,
    isNew: true,
    isTrending: false,
  },
  {
    title: 'Portal Escape 3D',
    description: 'เกมหลบหนี 3D ผ่านพอร์ทัลมหัศจรรย์ เก็บอัญมณี หลีกเลี่ยงกับดัก และพิชิตด่าน',
    thumbnail: '/api/games/33/thumbnail',
    gameUrl: '/games/portal-escape-3d.html',
    gameFile: null,
    isEmbedded: false,
    category: 'adventure',
    rating: 50,
    plays: 8900,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Dragon Flight 3D',
    description: 'เกมบินมังกร 3D สุดมันส์ พ่นไฟ เก็บอัญมณี บินผ่านภูเขาและเมฆ',
    thumbnail: '/api/games/34/thumbnail',
    gameUrl: '/games/dragon-flight-3d.html',
    gameFile: null,
    isEmbedded: false,
    category: 'action',
    rating: 50,
    plays: 15600,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Soccer Penalty Shootout',
    description: 'เกมยิงจุดโทษฟุตบอลสุดมันส์ เลือกทิศทาง ใช้พลัง และยิงเข้าประตู',
    thumbnail: '/api/games/35/thumbnail',
    gameUrl: '/games/soccer-penalty.html',
    gameFile: null,
    isEmbedded: false,
    category: 'sports',
    rating: 48,
    plays: 11200,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Basketball Shots 3D',
    description: 'เกมยิงบาสเกตบอล 3D ทดสอบทักษะการยิง มุมต่างๆ และระยะทางหลากหลาย',
    thumbnail: '/api/games/36/thumbnail',
    gameUrl: '/games/basketball-shots-3d.html',
    gameFile: null,
    isEmbedded: false,
    category: 'sports',
    rating: 47,
    plays: 9850,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Chess Master 3D',
    description: 'เกมหมากรุกคลาสสิก 3D เล่นกับ AI หรือเพื่อน ระดับความยากปรับได้',
    thumbnail: '/api/games/37/thumbnail',
    gameUrl: '/games/chess-master-3d.html',
    gameFile: null,
    isEmbedded: false,
    category: 'strategy',
    rating: 49,
    plays: 8750,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Medieval Kingdom Strategy',
    description: 'เกมกลยุทธ์สร้างอาณาจักรยุคกลาง สร้างกองทัพ ขยายดินแดน และพิชิตศัตรู',
    thumbnail: '/api/games/38/thumbnail',
    gameUrl: '/games/medieval-kingdom.html',
    gameFile: null,
    isEmbedded: false,
    category: 'strategy',
    rating: 50,
    plays: 13400,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Jungle Adventure Quest',
    description: 'ผจญภัยในป่าลึก เก็บสมบัติ หลบสัตว์ป่า ไขปริศนาโบราณ และค้นหาทางออก',
    thumbnail: '/api/games/39/thumbnail',
    gameUrl: '/games/jungle-adventure.html',
    gameFile: null,
    isEmbedded: false,
    category: 'adventure',
    rating: 48,
    plays: 10650,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Underwater Treasure Hunt',
    description: 'ดำน้ำลึกเพื่อหาสมบัติ หลบปลาฉลาม เก็บไข่มุก และสำรวจโลกใต้ทะเล',
    thumbnail: '/api/games/40/thumbnail',
    gameUrl: '/games/underwater-treasure.html',
    gameFile: null,
    isEmbedded: false,
    category: 'adventure',
    rating: 49,
    plays: 12800,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Mountain Climbing 3D',
    description: 'เกมปีนเขา 3D สุดท้าทาย เลือกเส้นทาง หลีกเลี่ยงอันตราย และไปถึงยอดเขา',
    thumbnail: '/api/games/41/thumbnail',
    gameUrl: '/games/mountain-climbing-3d.html',
    gameFile: null,
    isEmbedded: false,
    category: 'adventure',
    rating: 47,
    plays: 7900,
    isNew: true,
    isTrending: false,
  },
  {
    title: 'หนอนน้อย',
    description: 'เกมหนอนสไตล์ slither.io พร้อมฟีเจอร์พิเศษ ชนหางตัวเองได้ อาหารแม่เหล็ก และกราฟิกสวยงาม',
    thumbnail: '/api/games/38/thumbnail',
    gameUrl: '/games/หนอนน้อย.html',
    gameFile: null,
    isEmbedded: false,
    category: 'action',
    rating: 50,
    plays: 1250,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Gulper Snake',
    description: 'เกมงูสไตล์ gulper.io เคลื่อนไหวลื่น บูสต์ได้ มี AI บอท 6 สกิน และระบบลีดเดอร์บอร์ด',
    thumbnail: '/api/games/39/thumbnail',
    gameUrl: '/games/gulper-snake.html',
    gameFile: null,
    isEmbedded: false,
    category: 'action',
    rating: 50,
    plays: 0,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Rhythm Beat Master',
    description: 'เกมดนตรีเคาะจังหวะ ตามจังหวะเพลง สะสมคะแนน และปลดล็อกเพลงใหม่',
    thumbnail: '/api/games/42/thumbnail',
    gameUrl: '/games/rhythm-beat-master.html',
    gameFile: null,
    isEmbedded: false,
    category: 'casual',
    rating: 46,
    plays: 9200,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Word Search Puzzle',
    description: 'เกมหาคำศัพท์ในตาราง ฝึกสมอง เพิ่มพูนความรู้ และทดสอบความเร็วในการค้นหา',
    thumbnail: '/api/games/43/thumbnail',
    gameUrl: '/games/word-search-puzzle.html',
    gameFile: null,
    isEmbedded: false,
    category: 'puzzle',
    rating: 45,
    plays: 6800,
    isNew: true,
    isTrending: false,
  },
  {
    title: 'Dancing Beat Challenge',
    description: 'เกมเต้นตามจังหวะ เคลื่อนไหวตามแสง สะสมคะแนนเต้น และปลดล็อกเพลงใหม่',
    thumbnail: '/api/games/44/thumbnail',
    gameUrl: '/games/dancing-beat-challenge.html',
    gameFile: null,
    isEmbedded: false,
    category: 'casual',
    rating: 48,
    plays: 11500,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Cooking Master 3D',
    description: 'เกมทำอาหาร 3D จัดการร้านอาหาร ปรุงอาหารอร่อยและบริการลูกค้า',
    thumbnail: '/api/games/45/thumbnail',
    gameUrl: '/games/cooking-master-3d.html',
    gameFile: null,
    isEmbedded: false,
    category: 'casual',
    rating: 47,
    plays: 9300,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Fashion Designer Studio',
    description: 'เกมออกแบบแฟชั่น เลือกเสื้อผ้า แต่งตัวโมเดล และจัดแสดงแฟชั่นโชว์',
    thumbnail: '/api/games/46/thumbnail',
    gameUrl: '/games/fashion-designer-studio.html',
    gameFile: null,
    isEmbedded: false,
    category: 'casual',
    rating: 45,
    plays: 7800,
    isNew: true,
    isTrending: false,
  },
  {
    title: 'Pixel Art Creator',
    description: 'เกมวาดภาพพิกเซล สร้างสรรค์งานศิลปะ ระบายสี และแชร์ผลงาน',
    thumbnail: '/api/games/47/thumbnail',
    gameUrl: '/games/pixel-art-creator.html',
    gameFile: null,
    isEmbedded: false,
    category: 'casual',
    rating: 46,
    plays: 8600,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Neon Racing Circuit',
    description: 'เกมแข่งรถในเมืองอนาคต ไฟนีออน ความเร็วสูง และลูปแบบสามมิติ',
    thumbnail: '/api/games/48/thumbnail',
    gameUrl: '/games/neon-racing-circuit.html',
    gameFile: null,
    isEmbedded: false,
    category: 'racing',
    rating: 49,
    plays: 13200,
    isNew: true,
    isTrending: true,
  },
  {
    title: 'Desert Rally Championship',
    description: 'เกมแข่งรถในทะเลทราย ผ่านเนินทรายและโค้งอันตราย พร้อมรถที่หลากหลาย',
    thumbnail: '/api/games/49/thumbnail',
    gameUrl: '/games/desert-rally-championship.html',
    gameFile: null,
    isEmbedded: false,
    category: 'racing',
    rating: 48,
    plays: 10900,
    isNew: true,
    isTrending: true,
  },
  {
    title: "ASHURA Volleyball Advanced",
    description: "วอลเลย์บอลขั้นสูง พร้อมฟิสิกส์ลูกบอล Magnus Effect และ AI ที่ฉลาด",
    thumbnail: "/api/games/50/thumbnail",
    gameUrl: "/games/ashura-volleyball-advanced.html",
    gameFile: null,
    isEmbedded: false,
    category: "sports",
    plays: 12400,
    rating: 49,
    isNew: true,
    isTrending: true
  },
];

    defaultGames.forEach((gameData, index) => {
      const id = randomUUID();
      const game: Game = {
        id,
        title: gameData.title,
        description: gameData.description,
        thumbnail: gameData.thumbnail || '',
        gameUrl: gameData.gameUrl,
        gameFile: gameData.gameFile || null,
        isEmbedded: gameData.isEmbedded || false,
        category: gameData.category,
        rating: gameData.rating || 0,
        plays: gameData.plays || 0,
        isNew: gameData.isNew || false,
        isTrending: gameData.isTrending || false,
        createdAt: new Date()
      };
      this.games.set(id, game);
    });
  }

  async getAllGames(): Promise<Game[]> {
    return Array.from(this.games.values()).sort((a, b) => b.plays - a.plays);
  }

  async getGameById(id: string): Promise<Game | undefined> {
    return this.games.get(id);
  }

  async getGamesByCategory(category: string): Promise<Game[]> {
    return Array.from(this.games.values())
      .filter(game => game.category === category)
      .sort((a, b) => b.plays - a.plays);
  }

  async getTrendingGames(): Promise<Game[]> {
    return Array.from(this.games.values())
      .filter(game => game.isTrending)
      .sort((a, b) => b.plays - a.plays);
  }

  async getNewGames(): Promise<Game[]> {
    return Array.from(this.games.values())
      .filter(game => game.isNew)
      .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
  }

  async searchGames(query: string): Promise<Game[]> {
    const lowercaseQuery = query.toLowerCase();
    return Array.from(this.games.values())
      .filter(game => 
        game.title.toLowerCase().includes(lowercaseQuery) ||
        game.description.toLowerCase().includes(lowercaseQuery) ||
        game.category.toLowerCase().includes(lowercaseQuery)
      )
      .sort((a, b) => b.plays - a.plays);
  }

  async createGame(insertGame: InsertGame): Promise<Game> {
    const id = randomUUID();
    const game: Game = {
      id,
      plays: 0,
      createdAt: new Date(),
      ...insertGame,
      gameFile: insertGame.gameFile || null,
      isEmbedded: insertGame.isEmbedded || false,
      rating: insertGame.rating || 40,
      isNew: insertGame.isNew || false,
      isTrending: insertGame.isTrending || false
    };
    this.games.set(id, game);
    return game;
  }

  async updateGame(id: string, updates: Partial<Game>): Promise<Game | undefined> {
    const existing = this.games.get(id);
    if (!existing) return undefined;

    const updated = { ...existing, ...updates };
    this.games.set(id, updated);
    return updated;
  }

  async deleteGame(id: string): Promise<boolean> {
    return this.games.delete(id);
  }

  async incrementPlays(id: string): Promise<void> {
    const game = this.games.get(id);
    if (game) {
      game.plays += 1;
      this.games.set(id, game);
    }
  }
}

export const storage = new MemStorage();